### ISSUE TITLE
Highlighting of absolutely positioned children of ix:nonNumeric elements

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#139] opened 2020-09-16 12:34 UTC
Hi,

tagged textblock can not be highlighted in iXBLR previewer.

I have created two examples:
[V1.zip](https://github.com/Workiva/ixbrl-viewer/files/5232141/V1.zip) uses css classes. Highlighting doesn't work.
If I remove the property "class='...' ", it works

[V2.zip](https://github.com/Workiva/ixbrl-viewer/files/5232153/V2.zip) has the same document but don't uss css classes.

If I remove the property **position:absolute;** in css, it works as expected.

Can someone help ?

Kind regards,
Nachtinho

**Comment by paulwarren-wk** [comment] 2020-09-23 17:34
OK, to clarify, the issue is not the use of `class` attributes, but specifying `position: absolute` on an element within an `<ix:nonNumeric>` tag.  This is an issue whether it is done using `style` attributes or CSS classes.

The viewer doesn't currently support this, as it wraps the `<ix:nonNumeric>` tag with an additional element, and applies highlighting/borders to that.  Specifying `position: absolute` takes the enclosed element out of the flow of HTML elements, and so the rendered wrapper element is not actually wrapping anything.

This can be fixed within the document by placing the `<ix:nonNumeric>` element within the absolutely positioned element, and using `<ix:continuation>` if the tag spans multiple such elements.

I suspect this will be very hard to fix reliably within the viewer, as it would require detecting an separately such absolutely positioned elements.

**Comment by Nachtinho** [comment] 2020-09-24 12:32
yes, it seems be an issue in Preview and it is a valid HTML.  The workaround will blow up the HTML unnecessary. From my perspective it should be fixed in javascript, right ?

**Comment by beltistos87** [comment] 2021-02-03 16:51
Hi,
first of all I would like to thanks everybody for the subject in this topic, because it was very useful to find at least a workaround.
I was dealing with the same issue and using position:relative in the html code let to obtain highlight in the iXBRL preview. Unfortunately, introducing the relative position may affect the correct view of the page created by the html, i.e. words in relative position move around and the readibilty of the text is reduced. So I am forced to assign the position:relative only to a word or two in order to minimize the loss of readibility.
Do you find any new suggestion to solve this issue?

Kind regards,
Andrea

**Comment by Nachtinho** [comment] 2021-05-04 07:47
Hi,

Issue https://github.com/Workiva/ixbrl-viewer/issues/107 has been fixed.
But still no progress on this...

Regards,

**Comment by paulwarren-wk** [comment] 2021-05-04 13:39
Edited the summary to more accurately describe the issue.

Screenshot:
![image](https://user-images.githubusercontent.com/45077928/117011584-dff81d80-ace5-11eb-97a9-8368edd524bb.png)

The reliance on absolutely position div elements to layout normal paragraphs of text seems very undesirable.  As well as preventing correct highlighting of the iXBRL tags, it also interferes text selection behaviour in the browser.

**Closed** 2022-10-04 19:05 UTC
