### ISSUE TITLE
BUG: Empty fact followed by continuation breaks highlighting

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/ixbrl-viewer#341] opened 2022-12-01 20:05 UTC
If a fact is tagged as empty text ex:

```xml
<ix:nonNumeric xmlns:ix="http://www.xbrl.org/2013/inlineXBRL" contextRef="..." name="cipc-ca:DisclosureOfAuditCommitteesReportingExplanatory" id="..." continuedAt="i0f980b9ef16746afa879ee3a9ee923a7" escape="true"/></ix:nonNumeric>
```
and then continued later

```xml
<ix:continuation xmlns:ix="http://www.xbrl.org/2013/inlineXBRL" id="i0f980b9ef16746afa879ee3a9ee923a7">.....</ix:continuation>
```

the resulting ixbrl-viewer gets confused and thinks that the rest of the document is contained in the fact.

<img width="1012" alt="Screen Shot 2022-12-01 at 1 02 24 PM" src="https://user-images.githubusercontent.com/17255946/205148470-52a408eb-a6be-4d70-9d68-4517393fb670.png">

vs how it should look

<img width="1019" alt="Screen Shot 2022-12-01 at 1 04 14 PM" src="https://user-images.githubusercontent.com/17255946/205148847-7c1c07dc-a6bf-44e4-ba18-ecf04b079882.png">

[ixbrl-viewer-reproduction-filing.zip](https://github.com/Workiva/ixbrl-viewer/files/10135804/ixbrl-viewer-reproduction.zip)
[ixbrl_viewer_broken_example.zip](https://github.com/Workiva/ixbrl-viewer/files/10135897/ixbrl_viewer_broken_example.zip)

**Comment by brettkail-wk** [comment] 2022-12-01 20:18
This looks like self-closing tag issue: the issue is fixed if the XML is changed to an explicit closing tag `<ix:nonNumeric ...></ix:nonNumeric>` or if the file is renamed to `.xhtml`.  I suspect adjusting [this logic](https://github.com/Workiva/ixbrl-viewer/blob/15e5b458926092ab5533179302dc0cd99ede1bb9/iXBRLViewerPlugin/xhtmlserialize.py#L36) to `if m is None or` would fix the problem.

**Comment by paulwarren-wk** [comment] 2022-12-01 21:28
> I suspect adjusting [this logic](https://github.com/Workiva/ixbrl-viewer/blob/15e5b458926092ab5533179302dc0cd99ede1bb9/iXBRLViewerPlugin/xhtmlserialize.py#L36) to if m is None or would fix the problem.

That looks right to me.  For non-HTML tags, I think we can safely expand all self-closing tags.

**Comment by sagesmith-wf** [comment] 2022-12-02 17:11
I have been able to verify that this fixes the bug locally. I will go ahead and open the bug fix, thanks guys :)

**Comment by sagesmith-wf** [comment] 2022-12-02 17:19
Fixed it here https://github.com/Workiva/ixbrl-viewer/pull/342

**Closed** 2022-12-02 23:04 UTC
